"""initial schema

Revision ID: 55c46505a0e3
Revises: 
Create Date: 2026-08-08 20:09:28.807265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c46505a0e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cma_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('calc_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparable_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('square_feet', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Float(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('has_pool', sa.Boolean(), nullable=False),
    sa.Column('distance_from_subject', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('calc_version', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('list_price', sa.Float(), nullable=False),
    sa.Column('is_user_modified', sa.Boolean(), nullable=False),
    sa.Column('derived', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=30), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('has_pool', sa.Boolean(), nullable=False),
    sa.Column('renovation_notes', sa.Text(), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cma_id')
    )
    op.create_table('valuation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('calc_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('central_estimate', sa.Float(), nullable=True),
    sa.Column('low_estimate', sa.Float(), nullable=True),
    sa.Column('high_estimate', sa.Float(), nullable=True),
    sa.Column('median_adjusted', sa.Float(), nullable=True),
    sa.Column('weighted_ppsf', sa.Float(), nullable=True),
    sa.Column('dispersion', sa.Float(), nullable=True),
    sa.Column('cov', sa.Float(), nullable=True),
    sa.Column('included_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('per_comparable', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cma_id', sa.Integer(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('similarity_params', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('reconciliation', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cma_id'], ['cma_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cma_id')
    )
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparable_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject_value', sa.String(length=100), nullable=True),
    sa.Column('comparable_value', sa.String(length=100), nullable=True),
    sa.Column('unit_description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comparable_id'], ['comparable_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparable_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparable_id', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('similarity_breakdown', sa.JSON(), nullable=True),
    sa.Column('user_weight_multiplier', sa.Float(), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comparable_id'], ['comparable_properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparable_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparable_selections')
    op.drop_table('adjustments')
    op.drop_table('weight_configurations')
    op.drop_table('valuation_results')
    op.drop_table('subject_properties')
    op.drop_table('listing_strategies')
    op.drop_table('generated_reports')
    op.drop_table('comparable_properties')
    op.drop_table('audit_events')
    op.drop_table('cma_analyses')
    op.drop_table('users')
    # ### end Alembic commands ###
